"use client"

import Link from "next/link"
import { useState } from "react"
import { Menu, X } from "lucide-react"

export default function Navbar() {
  const [isOpen, setIsOpen] = useState(false)

    return (
        <header className="fixed top-0 left-0 w-full z-50 border-b border-white/10 bg-black/80 backdrop-blur-xl">
              <div className="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between">

                      {/* Logo */}
                              <Link
                                        href="/"
                                                  className="text-white text-xl md:text-2xl font-bold tracking-wide"
                                                          >
                                                                    AI World Hub
                                                                            </Link>

                                                                                    {/* Desktop Nav */}
                                                                                            <nav className="hidden md:flex items-center gap-8">
                                                                                                      <Link href="/" className="text-gray-300 hover:text-white transition-all duration-300">
                                                                                                                  Home
                                                                                                                            </Link>

                                                                                                                                      <Link href="/tools" className="text-gray-300 hover:text-white transition-all duration-300">
                                                                                                                                                  Tools
                                                                                                                                                            </Link>

                                                                                                                                                                      <Link href="/categories" className="text-gray-300 hover:text-white transition-all duration-300">
                                                                                                                                                                                  Categories
                                                                                                                                                                                            </Link>

                                                                                                                                                                                                      <Link href="/blogs" className="text-gray-300 hover:text-white transition-all duration-300">
                                                                                                                                                                                                                  Blogs
                                                                                                                                                                                                                            </Link>

                                                                                                                                                                                                                                      <Link href="/news" className="text-gray-300 hover:text-white transition-all duration-300">
                                                                                                                                                                                                                                                  News
                                                                                                                                                                                                                                                            </Link>
                                                                                                                                                                                                                                                                    </nav>

                                                                                                                                                                                                                                                                            {/* Mobile Menu Button */}
                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                              onClick={() => setIsOpen(!isOpen)}
                                                                                                                                                                                                                                                                                                        className="md:hidden text-white relative z-50"
                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                          {isOpen ? <X size={28} /> : <Menu size={28} />}
                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                              {/* Mobile Menu */}
                                                                                                                                                                                                                                                                                                                                                    <div
                                                                                                                                                                                                                                                                                                                                                            className={`md:hidden absolute top-16 left-0 w-full bg-black/95 backdrop-blur-xl border-t border-white/10 transition-all duration-300 ease-in-out overflow-hidden ${
                                                                                                                                                                                                                                                                                                                                                                      isOpen ? "max-h-[500px] opacity-100 py-4" : "max-h-0 opacity-0"
                                                                                                                                                                                                                                                                                                                                                                              }`}
                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex flex-col px-6 gap-5">

                                                                                                                                                                                                                                                                                                                                                                                                      <Link
                                                                                                                                                                                                                                                                                                                                                                                                                  href="/"
                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => setIsOpen(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                          className="text-gray-300 hover:text-white transition-all"
                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                Home
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                href="/tools"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={() => setIsOpen(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="text-gray-300 hover:text-white transition-all"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Tools
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              href="/categories"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={() => setIsOpen(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="text-gray-300 hover:text-white transition-all"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Categories
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            href="/blogs"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={() => setIsOpen(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="text-gray-300 hover:text-white transition-all"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Blogs
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          href="/news"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={() => setIsOpen(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="text-gray-300 hover:text-white transition-all"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        News
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </header>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }